apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-test
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-test
  template:
    metadata:
      labels:
        app: manual-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
